{{- range .Values.web }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .name }}"
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: "{{ .name }}"
    app.kubernetes.io/instance: "{{ $.Release.Name }}"
spec:
  replicas: {{ .replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .name }}"
      app.kubernetes.io/instance: "{{ $.Release.Name }}"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .name }}"
        app.kubernetes.io/instance: "{{ $.Release.Name }}"
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - image: {{ .image | default $.Values.image }}:{{ $.Values.version }}
        name: {{ .name }}
        ports:
        - name: {{ .portName | default "http" }}
          containerPort: {{ .port | default 8080 }}
          protocol: TCP
        {{- if .args}}
        command:
        {{- range .args }}
        - {{ . }}
        {{- end }}
        {{- end }}
        env:
        {{- range  $key, $value := $.Values.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        {{- range $.Values.secrets }}
        - name: {{ .name }}
          valueFrom:
            secretKeyRef:
              name: "{{ .from | default $.Values.defaultSecretName }}"
              key: {{ .name }}
        {{- end }}
{{- end -}}
